# Generated by Django 6.0.8 on 2026-10-04 12:24
"""Knowledge base: source documents and chunks with 1536-dimension embeddings, HNSW cosine index."""

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # core.0001 creates the vector extension (ADR 0003); the vector column needs it.
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('lang', models.CharField(max_length=2, verbose_name='language')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('license_note', models.TextField(blank=True, verbose_name='license note')),
            ],
            options={
                'verbose_name': 'source document',
                'verbose_name_plural': 'source documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question_number', models.PositiveIntegerField(verbose_name='question number')),
                ('kind', models.CharField(choices=[('question', 'Question'), ('summary', 'Summary'), ('answer', 'Answer')], max_length=10, verbose_name='kind')),
                ('lang', models.CharField(max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('text_norm', models.TextField(verbose_name='normalized text')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, verbose_name='embedding')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.sourcedocument', verbose_name='document')),
            ],
            options={
                'verbose_name': 'source chunk',
                'verbose_name_plural': 'source chunks',
                'ordering': ['document', 'question_number', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['document', 'question_number', 'kind'], name='chunk_question_kind'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
