# Generated by Django 6.0.8 on 2026-10-04 17:54

from django.db import migrations, models
from django.utils import timezone

# Values of knowledge/management/commands/ingest_bayyinat.py at the time of writing,
# copied so that the migration does not depend on code that may change.
BAYYINAT = {
    'url': 'https://dawa.center/file/7937',
    'pdf_url': 'https://dawa.center/storage/files/AMYj6DfmHlSnZ766Zz0VlBNwmYtdwhAl31XMETlT.pdf',
}


def set_bayyinat_urls(apps, schema_editor):
    """Give an already ingested Bayyinat its public page and PDF (no re-ingestion needed)."""
    SourceDocument = apps.get_model('knowledge', 'SourceDocument')
    SourceDocument.objects.filter(slug='bayyinat-ar').update(**BAYYINAT, updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Public PDF of the document, the same file that was ingested.', verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='url',
            field=models.URLField(blank=True, help_text='Public page of the document.', verbose_name='URL'),
        ),
        migrations.RunPython(set_bayyinat_urls, migrations.RunPython.noop),
    ]
