# Generated by Django 6.0.8 on 2026-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_source_document_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcechunk',
            name='kind',
            field=models.CharField(choices=[('question', 'Question'), ('summary', 'Summary'), ('answer', 'Answer'), ('glossary', 'Glossary term')], max_length=10, verbose_name='kind'),
        ),
    ]
