# Generated by Django 6.0.8 on 2026-10-04 08:14
"""
Initial schema of the core app: User, Center and Membership.

Edited after generation: VectorExtension is the first operation, so the
pgvector extension exists before any later migration needs the vector type
(ADR 0003). It is idempotent (CREATE EXTENSION IF NOT EXISTS) and needs a
role allowed to create extensions.
"""

import core.models.user
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public identifier')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('preferred_lang', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], default='en', max_length=2, verbose_name='preferred language')),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatars/', verbose_name='avatar')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Set when the user links their Telegram account.', null=True, unique=True, verbose_name='Telegram chat ID')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot log in. Deactivate accounts instead of deleting them.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can log in to the administration site.', verbose_name='staff status')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has confirmed their email address.', verbose_name='email verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'abstract': False,
            },
            managers=[
                ('objects', core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('logo', models.ImageField(blank=True, upload_to='centers/logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Telegram group where referred questions are sent, for example -1001234567890.', null=True, verbose_name='Telegram Group ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], max_length=2), blank=True, default=list, verbose_name='languages served')),
                ('is_default', models.BooleanField(default=False, help_text='Receives referred questions when no other center is selected.', verbose_name='default center')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'center',
                'verbose_name_plural': 'centers',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='only_one_default_center', violation_error_message='Only one center can be the default center.')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public identifier')),
                ('role', models.CharField(choices=[('specialist', 'Specialist'), ('center_admin', 'Center admin')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='left at')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='core.center', verbose_name='center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_ci', violation_error_message='A user with this email address already exists.'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'center'), name='unique_active_membership', violation_error_message='This user is already an active member of this center.'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('left_at__isnull', True)), models.Q(('is_active', False), ('left_at__isnull', False)), _connector='OR'), name='membership_active_matches_left_at', violation_error_message='An active membership cannot have a leaving date, and an inactive membership must have one.'),
        ),
    ]
