# Generated by Django 6.0.8 on 2026-10-04 09:23
"""
Center review: status, reviewer, review date and rejection reason (ADR 0013).

``status`` is added with the default ``approved``, so every existing center,
all created in the admin, becomes approved; self-registered centers are
created ``pending`` by the registration service.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to the applicant.', verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='center',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reviewed at'),
        ),
        migrations.AddField(
            model_name='center',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10, verbose_name='review status'),
        ),
        migrations.AlterField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to suspend an approved center.', verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('status', 'approved'), _connector='OR'), name='default_center_must_be_approved', violation_error_message='Only an approved center can be the default center.'),
        ),
    ]
