# Generated by Django 6.0.8 on 2026-10-04 11:39
"""Provider API keys, stored encrypted, one active per provider (ADR 0014)."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_center_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], max_length=20, verbose_name='provider')),
                ('name', models.CharField(help_text='For example: production key.', max_length=100, verbose_name='name')),
                ('encrypted_secret', models.TextField(editable=False, verbose_name='encrypted secret')),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True, verbose_name='fingerprint')),
                ('prefix', models.CharField(editable=False, max_length=3, verbose_name='prefix')),
                ('last_four', models.CharField(editable=False, max_length=4, verbose_name='last four characters')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='active')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='revoked at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('revoked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('provider',), name='one_active_credential_per_provider', violation_error_message='This provider already has an active API key.'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='credential_active_matches_revoked_at', violation_error_message='An active API key cannot have a revocation date, and a revoked one must have one.')],
            },
        ),
    ]
