# Generated by Django 6.0.8 on 2026-10-04 13:28
"""AISettings: chat model and temperature for the crews, one row (ADR 0016)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_api_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chat_model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model used by the crews, for example gpt-4o-mini.', max_length=100, verbose_name='chat model')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3, verbose_name='temperature')),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
