# Generated by Django 6.0.8 on 2026-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ai_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='verifier_model',
            field=models.CharField(blank=True, help_text='Model for the verifier step only, e.g. gpt-4o. Empty: the chat model.', max_length=100, verbose_name='verifier model'),
        ),
    ]
