# Generated by Django 6.0.8 on 2026-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ai_settings_verifier_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram group where referred questions are sent, for example -1001234567890. Set when a center admin connects the group through the bot.', null=True, verbose_name='Telegram Group ID'),
        ),
        migrations.AddConstraint(
            model_name='center',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id__isnull', False)), fields=('telegram_chat_id',), name='unique_center_telegram_group', violation_error_message='This Telegram group is already connected to another center.'),
        ),
    ]
