"""
Serializers for anonymous asking (ADR 0017): the question in, the answer out.

The answer is returned both as full text and as sentences, each with its supporting
quote and its Bayyinat source, so the UI can link every sentence to the book.
"""

from django.utils.translation import gettext_lazy as _
from drf_spectacular.utils import extend_schema_field
from rest_framework import serializers

from agents.replies import notes
from api.exceptions import AskingUnavailable, DailyCapacityReached
from knowledge.models import SourceChunk
from qa.models import Question

SESSION_PATTERN = r'^[A-Za-z0-9_-]{8,64}$'
TEXT_MIN, TEXT_MAX = 3, 2000


def session_field(**kwargs):
    """The ``session_id`` field: an opaque id generated by the frontend, never personal data."""
    return serializers.RegexField(
        SESSION_PATTERN, max_length=64,
        error_messages={'invalid': _('Use 8 to 64 letters, digits, "-" or "_".')}, **kwargs)


class AskSerializer(serializers.Serializer):
    """A new question. ``save()`` answers it and returns the saved ``Interaction``."""

    text = serializers.CharField(min_length=TEXT_MIN, max_length=TEXT_MAX)
    session_id = session_field()

    def create(self, validated_data):
        """
        Answer through ``agents.services.ask``.

        Raises ``DailyCapacityReached`` (429) past the global daily limit and
        ``AskingUnavailable`` (503) when the question could not be saved.
        """
        from agents.services import DailyLimitReached, ask  # loads CrewAI: only when asking

        request = self.context.get('request')
        user = getattr(request, 'user', None)
        asker = user if user is not None and user.is_authenticated else None
        try:
            interaction = ask(validated_data['text'], session_id=validated_data['session_id'], asker=asker)
        except DailyLimitReached:
            raise DailyCapacityReached from None
        if interaction.pk is None:
            raise AskingUnavailable
        return interaction


class SessionQuerySerializer(serializers.Serializer):
    """The ``session_id`` query parameter of the history."""

    session_id = session_field()


class PagesSerializer(serializers.Serializer):
    """Printed pages of a question in the book."""

    start = serializers.IntegerField(allow_null=True)
    end = serializers.IntegerField(allow_null=True)


class SourceSerializer(serializers.Serializer):
    """The Bayyinat question a sentence comes from."""

    number = serializers.IntegerField(help_text='Question number in the book.')
    title = serializers.CharField()
    pages = PagesSerializer(allow_null=True)
    url = serializers.CharField(help_text="The book's page on dawa.center, interface in the question's language.")
    pdf_url = serializers.CharField(help_text='The book PDF opened at the question\'s first page.')


class ReviewSerializer(serializers.Serializer):
    """Who stands behind a revised answer: the center, never the person (ADR 0020)."""

    center = serializers.CharField(help_text="The name of the center whose specialist revised the answer.")
    revised_at = serializers.DateTimeField(help_text='When the shown revision was written.')


class SentenceSerializer(serializers.Serializer):
    """One sentence of the answer, its supporting quote and its source."""

    text = serializers.CharField(help_text='Sentence without [Q<n>] markers.')
    quote = serializers.CharField(help_text='Supporting quote from the source, in Arabic.')
    source = SourceSerializer()


class NoteSerializer(serializers.Serializer):
    """A fixed note after the answer."""

    code = serializers.ChoiceField(choices=['partial', 'level_c'])
    text = serializers.CharField()


class VerificationSerializer(serializers.Serializer):
    """How many sentences the quote and entailment checks kept and removed."""

    kept = serializers.IntegerField()
    removed = serializers.IntegerField()


def describe_sources(pairs):
    """
    Source descriptions for ``(language, number)`` pairs, as ``{pair: dict}``.

    One query on the questions' ``question`` chunks; ``language`` only selects the
    interface language of the book page link. A number no longer in the knowledge
    base gets an empty description rather than an error.
    """
    numbers = {number for _language, number in pairs}
    chunks = (SourceChunk.objects.filter(question_number__in=numbers, kind=SourceChunk.Kind.QUESTION)
              .select_related('document').order_by('document__created_at'))
    found = {}
    for chunk in chunks:
        found.setdefault(chunk.question_number, chunk)
    sources = {}
    for language, number in pairs:
        chunk = found.get(number)
        if chunk is None:
            sources[(language, number)] = {'number': number, 'title': '', 'pages': None, 'url': '', 'pdf_url': ''}
            continue
        start, end = chunk.metadata.get('page_start'), chunk.metadata.get('page_end')
        sources[(language, number)] = {
            'number': number, 'title': chunk.title, 'pages': {'start': start, 'end': end},
            'url': chunk.document.page_url(language), 'pdf_url': chunk.document.pdf_page_url(start),
        }
    return sources


def load_sources(context, questions):
    """Describe, in ``context['sources']``, every source the ``questions`` cite and it lacks."""
    cache = context.setdefault('sources', {})
    wanted = {(question.lang, sentence['number'])
              for question in questions
              for sentence in getattr(getattr(question, 'interaction', None), 'sentences', [])} - set(cache)
    if wanted:
        cache.update(describe_sources(wanted))
    return cache


class QuestionListSerializer(serializers.ListSerializer):
    """Loads the sources of a whole page of questions in one query."""

    def to_representation(self, data):
        questions = list(data.all() if hasattr(data, 'all') else data)
        load_sources(self.child.context, questions)
        return [self.child.to_representation(question) for question in questions]


class QuestionSerializer(serializers.ModelSerializer):
    """A question and how it was answered. Identified by ``uuid``."""

    language = serializers.CharField(source='lang', help_text='ar, en or fr; empty if not detected.')
    level = serializers.SerializerMethodField(help_text='A, B, C, D or out_of_scope; null if not classified.')
    decision = serializers.SerializerMethodField(help_text='answer, partial, refer, abstain or out_of_scope.')
    answer = serializers.SerializerMethodField(help_text='Full answer text with [Q<n>] markers and notes.')
    sentences = serializers.SerializerMethodField()
    notes = serializers.SerializerMethodField()
    verification = serializers.SerializerMethodField()
    follow_up_number = serializers.SerializerMethodField(
        help_text='For a referred question: the number to quote when following up (its uuid).')
    answered_by = serializers.SerializerMethodField(
        help_text='ai: the AI answer with its sources; center: a specialist revised it (answer is their text, '
                  'without sentences or notes).')
    review = serializers.SerializerMethodField()

    class Meta:
        model = Question
        fields = ['uuid', 'session_id', 'text', 'language', 'level', 'decision', 'answer', 'answered_by', 'review',
                  'sentences', 'notes', 'verification', 'follow_up_number', 'created_at']
        read_only_fields = fields
        list_serializer_class = QuestionListSerializer

    @staticmethod
    def _interaction(question):
        return getattr(question, 'interaction', None)

    def get_level(self, question) -> str | None:
        interaction = self._interaction(question)
        return interaction.level if interaction else None

    def get_decision(self, question) -> str:
        interaction = self._interaction(question)
        return interaction.decision if interaction else ''

    def get_answer(self, question) -> str:
        revision = question.latest_revision()
        if revision:
            return revision.text
        interaction = self._interaction(question)
        return interaction.answer_text if interaction else ''

    def get_answered_by(self, question) -> str:
        return 'center' if question.latest_revision() else 'ai'

    @extend_schema_field(ReviewSerializer(allow_null=True))
    def get_review(self, question):
        revision = question.latest_revision()
        return {'center': question.center.name, 'revised_at': revision.created_at} if revision else None

    @extend_schema_field(SentenceSerializer(many=True))
    def get_sentences(self, question):
        if question.latest_revision():
            return []  # the revision replaces the AI answer and its sources
        cache = load_sources(self.context, [question])
        kept = getattr(self._interaction(question), 'sentences', [])
        return [{'text': s['text'], 'quote': s['quote'], 'source': cache[(question.lang, s['number'])]}
                for s in kept]

    @extend_schema_field(NoteSerializer(many=True))
    def get_notes(self, question):
        if question.latest_revision():
            return []
        interaction = self._interaction(question)
        return notes(interaction.decision, interaction.level, question.lang) if interaction else []

    @extend_schema_field(VerificationSerializer)
    def get_verification(self, question):
        interaction = self._interaction(question)
        return {'kept': len(interaction.sentences) if interaction else 0,
                'removed': len(interaction.dropped) if interaction else 0}

    def get_follow_up_number(self, question) -> str | None:
        interaction = self._interaction(question)
        return str(question.uuid) if interaction and interaction.decision == 'refer' else None
