# Generated by Django 6.0.8 on 2026-10-04 13:28
"""Questions, interactions and human labels (no personal data)."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_ai_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('out_of_scope', 'Out of scope')], max_length=12, null=True, verbose_name='level')),
                ('search_query', models.TextField(blank=True, verbose_name='search query')),
                ('retrieved', models.JSONField(blank=True, default=list, help_text='Ranked results: question number, score, chunk kind.', verbose_name='retrieved')),
                ('evidence_question_numbers', models.JSONField(blank=True, default=list, verbose_name='evidence question numbers')),
                ('answer_text', models.TextField(blank=True, verbose_name='answer')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='citations')),
                ('decision', models.CharField(choices=[('answer', 'Answer'), ('partial', 'Partial answer'), ('abstain', 'Abstain'), ('refer', 'Referred to a center'), ('out_of_scope', 'Out of scope')], max_length=12, verbose_name='decision')),
                ('verifier_verdict', models.CharField(blank=True, max_length=10, verbose_name='verifier verdict')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('prompt_version', models.CharField(blank=True, max_length=20, verbose_name='prompt version')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='latency (ms)')),
                ('tokens_in', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('tokens_out', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('error', models.TextField(blank=True, verbose_name='error')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('verdict', models.CharField(choices=[('approve', 'Approve'), ('correct', 'Correct'), ('reject', 'Reject')], max_length=10, verbose_name='verdict')),
                ('corrected_answer', models.TextField(blank=True, verbose_name='corrected answer')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='qa.interaction', verbose_name='interaction')),
            ],
            options={
                'verbose_name': 'human label',
                'verbose_name_plural': 'human labels',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='text')),
                ('lang', models.CharField(blank=True, max_length=5, verbose_name='language')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='session')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='core.center', verbose_name='center')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='qa.question', verbose_name='question'),
        ),
    ]
