# Generated by Django 6.0.8 on 2026-10-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ai_settings_verifier_model'),
        ('qa', '0002_question_uuid_sentences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(blank=True, help_text='The account that asked, when logged in. Empty for anonymous askers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='asker'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['asker', '-created_at'], name='question_asker_recent'),
        ),
    ]
