# Generated by Django 6.0.8 on 2026-10-05 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_question_asker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='answer')),
                ('reason', models.CharField(choices=[('correction', 'Correction of an error'), ('clarification', 'Clarification or completion'), ('specialist_answer', 'Answer by a specialist')], max_length=20, verbose_name='reason')),
                ('note', models.TextField(blank=True, help_text='For the center and staff only; never shown to the asker.', verbose_name='internal note')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='qa.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'answer revision',
                'verbose_name_plural': 'answer revisions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
