# Generated by Django 6.0.8 on 2026-10-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def open_referrals_of_referred_questions(apps, schema_editor):
    """
    Give every question referred before referrals existed its ticket (ADR 0021).

    The ticket keeps the question's date; it is answered, at the date of the
    newest revision, when a specialist already revised the answer, else open.
    """
    Question = apps.get_model('qa', 'Question')
    Referral = apps.get_model('qa', 'Referral')
    referred = Question.objects.filter(interaction__decision='refer', referral__isnull=True).select_related(
        'interaction')
    for question in referred:
        revision = question.revisions.order_by('-created_at').first()
        referral = Referral.objects.create(
            question=question, center_id=question.center_id,
            reason='level_d' if question.interaction.level == 'D' else 'no_evidence',
            status='answered' if revision else 'open', answered_at=revision.created_at if revision else None,
        )
        # auto_now_add set today's date; the ticket dates from the question
        Referral.objects.filter(pk=referral.pk).update(created_at=question.created_at, updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ai_settings_verifier_model'),
        ('qa', '0004_answer_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reason', models.CharField(choices=[('level_d', 'Personal ruling (level D)'), ('no_evidence', 'Not covered by the sources')], max_length=12, verbose_name='reason')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('answered', 'Answered'), ('closed', 'Closed without an answer')], default='open', max_length=12, verbose_name='status')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('close_note', models.TextField(blank=True, help_text='Why the center closed it without an answer; never shown to the asker.', verbose_name='closing note')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='core.center', verbose_name='center')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='qa.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'referral',
                'verbose_name_plural': 'referrals',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['center', 'status', '-created_at'], name='referral_center_queue')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'answered'), _negated=True), ('answered_at__isnull', False), _connector='OR'), name='referral_answered_has_date', violation_error_message='An answered referral needs the date of its answer.'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'closed'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='referral_closed_has_date', violation_error_message='A closed referral needs the date it was closed.')],
            },
        ),
        migrations.RunPython(open_referrals_of_referred_questions, migrations.RunPython.noop),
    ]
