# Generated by Django 6.0.8 on 2026-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='live_until',
            field=models.DateTimeField(blank=True, help_text='End of the live window in which specialists are expected to answer at once.', null=True, verbose_name='live until'),
        ),
    ]
