# Generated by Django 6.0.8 on 2026-10-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_referral_live_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='mode',
            field=models.CharField(choices=[('live', 'Asked a specialist now'), ('ticket', 'Saved as a ticket')], default='live', max_length=8, verbose_name='mode'),
        ),
    ]
