# Generated by Django 6.0.8 on 2026-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_referral_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Machine translations of the question for specialists, by language code.', verbose_name='translations'),
        ),
    ]
