# Generated by Django 6.0.8 on 2026-10-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_question_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
    ]
