# Generated by Django 6.0.8 on 2026-10-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_referral_verbose_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='evidence',
            field=models.TextField(blank=True, help_text='The exact evidence text the writer received; empty for fixed replies.', verbose_name='evidence given to the writer'),
        ),
    ]
