# Generated by Django 6.0.8 on 2026-10-06 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_interaction_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanlabel',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI verdict', 'verbose_name_plural': 'AI verdicts'},
        ),
        migrations.AlterField(
            model_name='humanlabel',
            name='verdict',
            field=models.CharField(choices=[('approve', 'Correct'), ('correct', 'To correct'), ('reject', 'Wrong')], max_length=10, verbose_name='verdict'),
        ),
        migrations.AddConstraint(
            model_name='humanlabel',
            constraint=models.UniqueConstraint(fields=('interaction', 'reviewer'), name='one_label_per_reviewer', violation_error_message='This reviewer already gave a verdict on this answer.'),
        ),
    ]
