# Generated by Django 6.0.8 on 2026-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_label_verdicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrevision',
            name='lang',
            field=models.CharField(blank=True, max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='translated_text',
            field=models.TextField(blank=True, help_text="AI translation of the answer into the question's language, when the specialist wrote in another.", verbose_name='translation for the asker'),
        ),
    ]
