# Generated by Django 6.0.8 on 2026-10-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa', '0005_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('referral_notice', 'New referral notice')], max_length=20, verbose_name='kind')),
                ('chat_id', models.BigIntegerField(verbose_name='chat ID')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='message ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10, verbose_name='status')),
                ('text', models.TextField(verbose_name='text')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='qa.referral', verbose_name='referral')),
            ],
            options={
                'verbose_name': 'Telegram message',
                'verbose_name_plural': 'Telegram messages',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='telegram_message_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('message_id__isnull', False), _connector='OR'), name='telegram_sent_has_message_id', violation_error_message='A sent Telegram message needs its message ID.')],
            },
        ),
    ]
