# Generated by Django 6.0.8 on 2026-10-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_center_unique_telegram_group'),
        ('telegram_bot', '0002_link_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlinkcode',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.center', verbose_name='center'),
        ),
    ]
