# Generated by Django 6.0.8 on 2026-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_link_code_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='kind',
            field=models.CharField(choices=[('referral_notice', 'New referral notice'), ('answer_prompt', 'Answer prompt')], max_length=20, verbose_name='kind'),
        ),
    ]
