"""
Anonymous asking (ADR 0017): ask a question, read a session's history, read one question.

No login and no personal data: questions are grouped by a ``session_id`` the
frontend generates. Asking is throttled per IP and by a global daily limit.
Views stay thin: ``AskSerializer`` validates and calls ``agents.services.ask``.
"""

from django.utils.translation import gettext_lazy as _
from drf_spectacular.utils import OpenApiParameter, extend_schema
from rest_framework import exceptions, generics, permissions, status
from rest_framework.response import Response

from api.throttling import AskDayThrottle, AskMinuteThrottle
from api.v1.serializers.questions import AskSerializer, QuestionSerializer, SessionQuerySerializer
from qa.models import Question


class AnonymousMixin:
    """
    Open to everyone, with no authentication at all.

    Authentication is disabled, not only optional, so a stale token sent by a
    client cannot turn a public request into a 401.
    """

    authentication_classes = []
    permission_classes = [permissions.AllowAny]


@extend_schema(tags=['questions'])
class QuestionListCreateView(AnonymousMixin, generics.ListCreateAPIView):
    """Ask a question (POST), or list the questions of one session (GET)."""

    serializer_class = QuestionSerializer
    throttle_classes = [AskMinuteThrottle, AskDayThrottle]  # POST only (api/throttling.py)

    def get_queryset(self):
        """The session's questions, newest first; ``session_id`` is required."""
        if 'session_id' not in self.request.query_params:
            raise exceptions.ValidationError({'detail': exceptions.ErrorDetail(
                _('The session_id query parameter is required.'), code='session_required')})
        query = SessionQuerySerializer(data=self.request.query_params)
        query.is_valid(raise_exception=True)
        return Question.objects.for_session(query.validated_data['session_id']).select_related('interaction')

    @extend_schema(parameters=[OpenApiParameter('session_id', str, required=True,
                                                description='Session id generated by the frontend.')])
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @extend_schema(request=AskSerializer, responses={201: QuestionSerializer})
    def post(self, request, *args, **kwargs):
        """Answer the question; waits for the answer (about 20 to 45 s)."""
        serializer = AskSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        interaction = serializer.save()
        data = QuestionSerializer(interaction.question, context=self.get_serializer_context()).data
        return Response(data, status=status.HTTP_201_CREATED)


@extend_schema(tags=['questions'])
class QuestionDetailView(AnonymousMixin, generics.RetrieveAPIView):
    """One question by its uuid, for example a referred question followed up later."""

    serializer_class = QuestionSerializer
    queryset = Question.objects.select_related('interaction')
    lookup_field = 'uuid'
