"""
Asking (ADR 0017, ADR 0019): ask a question, read a session's history, read one
question, and, when logged in, read one's own questions.

No login needed: questions are grouped by a ``session_id`` the frontend
generates. When the request carries a valid access token, the question is also
linked to that account. Asking is throttled per IP and by a global daily limit.
Views stay thin: ``AskSerializer`` validates and calls ``agents.services.ask``.
"""

from django.utils.translation import gettext_lazy as _
from drf_spectacular.utils import OpenApiParameter, extend_schema
from rest_framework import exceptions, generics, permissions, status
from rest_framework.response import Response

from api.authentication import OptionalJWTAuthentication
from api.throttling import AskDayThrottle, AskMinuteThrottle
from api.v1.serializers.questions import (
    AskSerializer, QuestionSerializer, SessionQuerySerializer, SpecialistRequestSerializer,
)
from qa.models import Question
from qa.services import request_specialist


class PublicMixin:
    """
    Open to everyone; a valid access token identifies the user, nothing more.

    Authentication is optional and never fails (``OptionalJWTAuthentication``),
    so a stale token sent by a client cannot turn a public request into a 401.
    """

    authentication_classes = [OptionalJWTAuthentication]
    permission_classes = [permissions.AllowAny]


@extend_schema(tags=['questions'])
class QuestionListCreateView(PublicMixin, generics.ListCreateAPIView):
    """Ask a question (POST), or list the questions of one session (GET)."""

    serializer_class = QuestionSerializer
    throttle_classes = [AskMinuteThrottle, AskDayThrottle]  # POST only (api/throttling.py)

    def get_queryset(self):
        """The session's questions, newest first; ``session_id`` is required."""
        if 'session_id' not in self.request.query_params:
            raise exceptions.ValidationError({'detail': exceptions.ErrorDetail(
                _('The session_id query parameter is required.'), code='session_required')})
        query = SessionQuerySerializer(data=self.request.query_params)
        query.is_valid(raise_exception=True)
        return Question.objects.for_session(query.validated_data['session_id']).with_answers()

    @extend_schema(parameters=[OpenApiParameter('session_id', str, required=True,
                                                description='Session id generated by the frontend.')])
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    @extend_schema(request=AskSerializer, responses={201: QuestionSerializer})
    def post(self, request, *args, **kwargs):
        """Answer the question; waits for the answer (about 20 to 45 s). Logged in: linked to the account."""
        serializer = AskSerializer(data=request.data, context=self.get_serializer_context())
        serializer.is_valid(raise_exception=True)
        interaction = serializer.save()
        data = QuestionSerializer(interaction.question, context=self.get_serializer_context()).data
        return Response(data, status=status.HTTP_201_CREATED)


@extend_schema(tags=['questions'])
class QuestionDetailView(PublicMixin, generics.RetrieveAPIView):
    """One question by its uuid, for example a referred question followed up later."""

    serializer_class = QuestionSerializer
    queryset = Question.objects.with_answers()
    lookup_field = 'uuid'


@extend_schema(tags=['questions'], request=SpecialistRequestSerializer, responses={201: QuestionSerializer})
class SpecialistRequestView(PublicMixin, generics.GenericAPIView):
    """
    Send a question the AI did not answer to the specialists: live, or as a ticket.

    Only the asker: the logged-in account that asked, or the same ``session_id``
    for an anonymous question; anyone else gets 404, as if the question did not
    exist. Throttled like asking. A logged-in asker sending a question they asked
    anonymously (same ``session_id``) claims it: it is linked to their account, so
    the answer also appears in ``me/questions/`` on every device.
    """

    serializer_class = SpecialistRequestSerializer
    throttle_classes = [AskMinuteThrottle, AskDayThrottle]

    def post(self, request, uuid):
        body = SpecialistRequestSerializer(data=request.data)
        body.is_valid(raise_exception=True)
        question = Question.objects.filter(uuid=uuid).first()
        if question is None or not self._owns(request, question, body.validated_data.get('session_id', '')):
            raise exceptions.NotFound
        if request.user.is_authenticated and question.asker_id is None:
            question.asker = request.user
            question.save(update_fields=['asker', 'updated_at'])
        request_specialist(question, body.validated_data['mode'])
        question = Question.objects.with_answers().get(pk=question.pk)
        return Response(QuestionSerializer(question, context=self.get_serializer_context()).data,
                        status=status.HTTP_201_CREATED)

    @staticmethod
    def _owns(request, question, session_id):
        """The asker: their account when logged in, or the session that asked."""
        if question.asker_id is not None:
            return request.user.is_authenticated and request.user.pk == question.asker_id
        return bool(session_id) and session_id == question.session_id


@extend_schema(tags=['me'])
class MyQuestionsView(generics.ListAPIView):
    """The questions the caller asked while logged in, from any device, newest first."""

    serializer_class = QuestionSerializer

    def get_queryset(self):
        return Question.objects.for_asker(self.request.user).with_answers()
